config/routes.rb
Rails.application.routes.draw do
  resources :advertisments
  resources :variants
  resources :brands
  devise_for :users
  get 'home/index'

  root to: "advertisments#index"
end

app/models/advertisment.rb
class Advertisment < ApplicationRecord
  belongs_to :brand
  belongs_to :user
  belongs_to :variant
end

app/controllers/advertisments_controller.rb
class AdvertismentsController < ApplicationController
  before_action :set_advertisment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  @brands= Brand.all
  @variants = Variant.all
  # GET /advertisments
  # GET /advertisments.json
  def index
    @advertisments = Advertisment.all
    @variants = Variant.all
    @users = User.all
    @brands = Brand.all
    @brs = params['brand_id'].to_i
    
    @year = params['year'].to_i
    @distance = params['mileage'].to_i
    @price = [params['price_min'].to_i, params['price_max'].to_i]
    @f = params['fueltyp'].to_i - 1
    if(@brs !=0 ||@year !=0 || @distance != 0|| @price != 0)
      if(@brs != 0)
        @advertisments = @advertisments.where('brand_id = ?', @brs)
      end
      if(@year > 1950 && @year < 2050)
        @advertisments = @advertisments.where('year > ?', @year)
      end
      if(@f == 1 || @f == 0)
        @advertisments = @advertisments.where('fueltype = ?', @f)
      end
      if(@distance != 0)
        @advertisments = @advertisments.where('kmdriven < ?', @distance)
      end
      if(@price[0] != 0)
        @advertisments = @advertisments.where('price > ?', @price[0])
      end
      if(@price[1] != 0)
        @advertisments = @advertisments.where('price < ?', @price[1])
      end
    end
    
  end

  # GET /advertisments/1
  # GET /advertisments/1.json
  def show
    @brands = Brand.all
    @variants = Variant.all
  end

  # GET /advertisments/new
  def new
    @advertisment = Advertisment.new
    @brands = Brand.all
    @variants = Variant.all
  end

  # GET /advertisments/1/edit
  def edit
    @advertisment = Advertisment.new
    @brands = Brand.all
    @variants = Variant.all
  end

  # POST /advertisments
  # POST /advertisments.json
  def create
    @advertisment = Advertisment.new(advertisment_params)
    @advertisment.user_id = current_user.id
    @advertisment.brand_id = params[:brand_id]
    @advertisment.variant_id = params[:varientid]
    respond_to do |format|
      if @advertisment.save
        format.html { redirect_to @advertisment, notice: 'Advertisment was successfully created.' }
        format.json { render :show, status: :created, location: @advertisment }
      else
        format.html { render :new }
        format.json { render json: @advertisment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisments/1
  # PATCH/PUT /advertisments/1.json
  def update
    respond_to do |format|
      if @advertisment.update(advertisment_params)
        format.html { redirect_to @advertisment, notice: 'Advertisment was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertisment }
      else
        format.html { render :edit }
        format.json { render json: @advertisment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisments/1
  # DELETE /advertisments/1.json
  def destroy
    @advertisment.destroy
    respond_to do |format|
      format.html { redirect_to advertisments_url, notice: 'Advertisment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisment
      @advertisment = Advertisment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisment_params
      params.require(:advertisment).permit(:year, :kmdriven, :ownercount, :price, :color, :fueltype, :brand_id, :user_id, :variant_id)
    end
end

app/helpers/advertisments_helper.rb
module AdvertismentsHelper
end

app/views/advertisments/_form.html.erb
<%= form_with(model: advertisment, local: true) do |form| %>
  <% if advertisment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advertisment.errors.count, "error") %> prohibited this advertisment from being saved:</h2>

      <ul>
      <% advertisment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :advertisment_year %>
  </div>

  <div class="field">
    <%= form.label :kmdriven %>
    <%= form.text_field :kmdriven, id: :advertisment_kmdriven %>
  </div>

  <div class="field">
    <%= form.label :ownercount %>
    <%= form.number_field :ownercount, id: :advertisment_ownercount %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :advertisment_price %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :advertisment_color %>
  </div>

  <div class="field">
    <%= form.label :fueltype %>
    <%= form.number_field :fueltype, id: :advertisment_fueltype %>
  </div>

  <div class="field">
    <select id="brandss" name="brand_id" class="form-control" >
		 <option value ="0">none</option>
		 <% @brands.find_each do |brand| %>
											  
		  <option value = "<%= brand.id %>"><%= brand.name %></option>
	  <% end %>
		</select>
  </div>


  <div class="field">
    <select id="variantss" name="varientid" class="form-control" >
											<% @variants.find_each do |variant| %>
											
						<option value = "<%= variant.id %>" ><%= variant.model%></option>
				      
		  <% end %>
		  </select>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advertisments/edit.html.erb
<h1>Editing Advertisment</h1>

<%= render 'form', advertisment: @advertisment %>

<%= link_to 'Show', @advertisment %> |
<%= link_to 'Back', advertisments_path %>

app/views/advertisments/index.html.erb
<p id="notice"><%= notice %></p>

 <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!-- Include the plugin's CSS and JS: -->
<script type="text/javascript" src="http://davidstutz.github.io/bootstrap-multiselect/dist/js/bootstrap-multiselect.js"></script>
<style type="text/css">
@import url("http://davidstutz.github.io/bootstrap-multiselect/dist/css/bootstrap-multiselect.css");
</style>
 <script type="text/javascript">
 		function showHideFilter(){
			var filterTable = document.getElementById("filterBody")
 			if(filterTable.offsetLeft <= 0){
 				filterTable.setAttribute("style","");
 			}else{
 				 filterTable.setAttribute("style","display:none");

 			}
 		}
 </script>
  <script>

function addvalues()
{
	var i =0;
	 var brandList = document.getElementById("brandss");
    var variantList = document.getElementById("variantss");
    for(; i<variantList.options.length;i++)
    {
    	
    	window.BrandAndVariant[variantList.options[i].value].push(variantList.options[i].name);
    }
   
    brandList.options.add()
}
       </script>                            
       <script>
function ChangeCarList() {
    var brandList = document.getElementById("brandss");
    var variantList = document.getElementById("variantss");
    var selBra = brandList.options[brandList.selectedIndex].value;
    
    while (variantList.options.length) {
        variantList.remove(0);
    }
    
    var brands = window.BrandAndVariant[selBra];
    if (brands) {
        var i;
        for (i = 0; i < brands.length; i++) {
            var brand = new Option((brands[i]));
            
            variantList.options.add(brand);
        }
    }
} 

				         </script>

<div class="container"> <br />
    <br />
    <h1>Advertisments</h1>
	<div class="row">
	
		<div class="panel panel-primary filterable">
			<div class="panel-heading">
    			<div class="pull-right">
					<button class="btn btn-default btn-xs btn-filter" id="filterButton" onclick="showHideFilter()"><span class="glyphicon glyphicon-filter"></span> Filter</button>
				</div>
				<h3 class="panel-title">Filter</h3>
			</div>
			<table class="table" id="filterBody" style="display:none">
				<thead>
					<tr class="filter">
					    <th class="column-01"></th>
						<th class="column-01"> </th>
						<th class="column-01"><p class="columnHeading">Brand</p>
						  	<form class="form-inline" role="form">
								<div class="btn-group">
								<div class="input-group"> 
											<select id="brandss" name="brand_id" class="form-control" onchange="ChangeCarList()" >
											   <option value ="0">none</option>
											   <% @brands.find_each do |brand| %>
											  
											    <option value = "<%= brand.id %>"><%= brand.name %></option>
											    <% end %>
											</select>
					<!--	<th class="column-02"></th>
						<th class="column-02"> </th>
						<th class="column-02"><p class="columnHeading">Model</p>
						  	<form class="form-inline" role="form">
								<div class="btn-group">
								<div class="input-group"> 
								<select id="variantss" name="Brand id" class="form-control" >
											<% @variants.find_each do |variant| %>
											<% @b =  @brands.find(variant.brand_id) %>
						<option value = "<%= variant.brand_id %>" disabled= "true"><%= variant.model%></option>
				      
				    <% end %>
						    </select>
						    <form action= "/advertisements/advertisement_params " method="post">-->
						    
						<th class="column-03"></th>
						<th class="column-03"> </th>
						<th class="column-03"><p class="columnHeading ">Year</p>
						  	<form class="form-inline" role="form">
								<div class="btn-group" onload="addvalues()">
								<div class="input-group"> 
											<input name="year" id="year" class="form-control input-number" type="number">	
						<th class="column-04"></th>
						<th class="column-04"> </th>
						<th class="column-04"><p class="columnHeading">Mileage</p>
						  	<form class="form-inline" role="form">
								<div class="btn-group">
								<div class="input-group"> 
											<input name="mileage" id="mileage" class="form-control input-number" type="number">		
						<th class="column-05"></th>
						<th class="column-05"> </th>
						<th class="column-05"><p class="columnHeading">Price</p>
						  	<form class="form-inline" role="form">
								<div class="btn-group">
								<div class="input-group"> 
								<div>min
											<input name="price_min" id="price_min" class="form-control input-number" type="" min="1000" max="120000" >
									</div>
									<div>
											- max 
									<input name="price_max" id="price_max" class="form-control input-number" type="text" min="0" max="120000" >
								
									</div>
								</div>
							<th class="column-06"></th>
						<th class="column-06"> </th>
						<th class="column-06"><p class="columnHeading">FuelType</p>
						  	<form class="form-inline" role="form">
								<div class="btn-group">
								<div class="input-group"> 
											<select id="fueltyp" name="fueltyp" class="form-control" >
											
										<option value="0">none</option>	
						<option value = 1>Petrol</option>
						<option value = 2>Diesel</option>
				      
				   
						    </select>
											<th class="column-06"></th>
						<th class="column-07"> </th>
						<th class="column-07"><p class="columnHeading"></p>
						  	<form class="form-inline" role="form">
								<div class="btn-group">
								<div class="input-group"> 
									<button class="btn btn-control btn-submit">Filter</button>
										     
						
					
								
									</div>
								</div>
						
									</div>
								</div>
							</form>
						</th>
					</tr>
				</thead>
				<tbody>
			</table>
		</div>
	</div>


<% @advertisments.each do |advertisment| %>
	<% @b = @brands.find(advertisment.brand_id).name %>
	<% @v = @variants.find(advertisment.variant_id).model %>
	<% @car = @b + " " + @v %>
<div class="row">
  <div class="col-sm-2">
    <img src=<%= BingImageSearch.imageurl("264b7272e3044807a5f19434a3e8dc8a", @car,1)%> class="media-object" style="width:150px;height:150px">
  </div>
  <div class="col-sm-10">
	<h3 > <%= link_to @car , advertisment %></h3>
	<div class="row">
		<div class="col-sm-2">
			<b>Year</b>
			<p><%= advertisment.year %></p>
		</div>
	
    
		<div class="col-sm-2">
			<b>KM Driven</b>
			<p><%= advertisment.kmdriven %></p>
		</div>
		<div class="col-sm-2">
			<b>Owner Count</b>
			<p><%= advertisment.ownercount %></p>
		</div>
		<div class="col-sm-2">
			<b>Fuel Type</b>
			<% if(advertisment.fueltype == 0) %>
        		<p>Petrol</p>
        	<%else%>
        		<p>Diesel</p>
        <% end%>
		</div>
		<div class="col-sm-2">
			<b> Colour</b>
			<p><%= advertisment.color %></p>
		</div>
		<div class="col-sm-2">
			<b> Price</b>
			<p>€ <%= advertisment.price %></p>
		</div>
	</div>
	
  </div>
</div>
<br>
<% end %>


<%= link_to 'New Advertisment', new_advertisment_path %>

app/views/advertisments/new.html.erb
<h1>New Advertisment</h1>

<%= render 'form', advertisment: @advertisment %>

<%= link_to 'Back', advertisments_path %>

app/views/advertisments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @advertisment.year %>
</p>

<p>
  <strong>Kmdriven:</strong>
  <%= @advertisment.kmdriven %>
</p>

<p>
  <strong>Ownercount:</strong>
  <%= @advertisment.ownercount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @advertisment.price %>
</p>

<p>
  <strong>Color:</strong>
  <%= @advertisment.color %>
</p>

<p>
  <strong>Fueltype:</strong>
  <%= @advertisment.fueltype %>
</p>

<p>
  <strong>Brand:</strong>
  <% @b = @brands.find(@advertisment.brand_id).name %>
</p>


<p>
  <strong>Variant:</strong>
  <%= @variants.find(@advertisment.variant_id).model %>
</p>


<%= link_to 'Back', advertisments_path %>